// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package alipay_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AlipayMerchantAppConfig is the golang structure for table alipay_merchant_app_config.
type AlipayMerchantAppConfig struct {
	Id                      int64       `json:"id"                      orm:"id"                          description:"商家id"`
	Name                    string      `json:"name"                    orm:"name"                        description:"商家name"`
	AppId                   string      `json:"appId"                   orm:"app_id"                      description:"商家应用Id"`
	AppName                 string      `json:"appName"                 orm:"app_name"                    description:"商家应用名称"`
	AppType                 int         `json:"appType"                 orm:"app_type"                    description:"应用类型：1小程序  2网站/移动应用  4生活号"`
	AppAuthToken            string      `json:"appAuthToken"            orm:"app_auth_token"              description:"商家授权应用token"`
	IsFullProxy             int         `json:"isFullProxy"             orm:"is_full_proxy"               description:"是否全权委托待开发：0否 1是"`
	State                   int         `json:"state"                   orm:"state"                       description:"状态：0禁用 1启用"`
	ExpiresIn               *gtime.Time `json:"expiresIn"               orm:"expires_in"                  description:"Token失效时间"`
	ReExpiresIn             *gtime.Time `json:"reExpiresIn"             orm:"re_expires_in"               description:"Token刷新限期时间"`
	UserId                  string      `json:"userId"                  orm:"user_id"                     description:"应用所属账号"`
	UnionMainId             int64       `json:"unionMainId"             orm:"union_main_id"               description:"关联主体id"`
	SysUserId               int64       `json:"sysUserId"               orm:"sys_user_id"                 description:"用户id"`
	ExtJson                 string      `json:"extJson"                 orm:"ext_json"                    description:"拓展字段"`
	AppGatewayUrl           string      `json:"appGatewayUrl"           orm:"app_gateway_url"             description:"网关地址"`
	AppCallbackUrl          string      `json:"appCallbackUrl"          orm:"app_callback_url"            description:"回调地址"`
	AesEncryptKey           string      `json:"aesEncryptKey"           orm:"aes_encrypt_key"             description:"AES接口内容加密方式"`
	ServerDomain            string      `json:"serverDomain"            orm:"server_domain"               description:"服务器域名"`
	Logo                    string      `json:"logo"                    orm:"logo"                        description:"商家应用logo"`
	HttpsCert               string      `json:"httpsCert"               orm:"https_cert"                  description:"域名证书"`
	HttpsKey                string      `json:"httpsKey"                orm:"https_key"                   description:"域名私钥"`
	PrivateKey              string      `json:"privateKey"              orm:"private_key"                 description:"私钥"`
	PublicKey               string      `json:"publicKey"               orm:"public_key"                  description:"公钥"`
	PublicKeyCert           string      `json:"publicKeyCert"           orm:"public_key_cert"             description:"公钥证书"`
	AppPublicCertKey        string      `json:"appPublicCertKey"        orm:"app_public_cert_key"         description:"应用证书公钥"`
	AlipayRootCertPublicKey string      `json:"alipayRootCertPublicKey" orm:"alipay_root_cert_public_key" description:"阿里根证书公钥"`
	DevState                int         `json:"devState"                orm:"dev_state"                   description:"开发状态：0未上线 1已上线"`
	InterfaceSignType       int         `json:"interfaceSignType"       orm:"interface_sign_type"         description:"接口加签方式：1密钥 2证书"`
	UpdatedAt               *gtime.Time `json:"updatedAt"               orm:"updated_at"                  description:""`
	AppIdMd5                string      `json:"appIdMd5"                orm:"app_id_md5"                  description:"应用id加密md5后的结果"`
	ThirdAppId              string      `json:"thirdAppId"              orm:"third_app_id"                description:"服务商appId"`
	NotifyUrl               string      `json:"notifyUrl"               orm:"notify_url"                  description:"异步通知地址，允许业务层追加相关参数"`
	ServerRate              float64     `json:"serverRate"              orm:"server_rate"                 description:"手续费比例，默认0.006%"`
	UnionMainType           int         `json:"unionMainType"           orm:"union_main_type"             description:"应用关联主体类型，和user_type保持一致"`
	Version                 string      `json:"version"                 orm:"version"                     description:"应用版本"`
	PrivacyPolicy           string      `json:"privacyPolicy"           orm:"privacy_policy"              description:"隐私协议"`
	UserPolicy              string      `json:"userPolicy"              orm:"user_policy"                 description:"用户协议"`
}
