// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
    _ "github.com/kysion/alipay-library/internal/logic/gateway"
    _ "github.com/kysion/alipay-library/internal/logic/merchant"
)
