// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package alipay_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AlipayConsumerConfig is the golang structure of table alipay_consumer_config for DAO operations like Where/Data.
type AlipayConsumerConfig struct {
	g.Meta             `orm:"table:alipay_consumer_config, do:true"`
	Id                 interface{} // id
	UserId             interface{} // 用户账号id
	SysUserId          interface{} // 用户id
	Avatar             interface{} // 头像
	Province           interface{} // 省份
	City               interface{} // 城市
	NickName           interface{} // 昵称
	IsStudentCertified interface{} // 学生认证
	UserType           interface{} // 用户账号类型
	UserState          interface{} // 状态：0未激活、1正常、-1封号、-2异常、-3已注销
	IsCertified        interface{} // 是否实名认证
	Sex                interface{} // 性别：0女 1男
	AuthToken          interface{} // 授权token
	ExtJson            interface{} // 拓展字段
	AuthState          interface{} // 用户授权状态：1授权、2未授权
	AlipayUserId       interface{} // Alipay的UserId
	ExpiresIn          *gtime.Time // 用户授权Token过期时间
	ReFreshToken       interface{} // 刷新Token
	ReExpiresIn        *gtime.Time // 刷新Token过期时间
	AuthStart          *gtime.Time // 用户授权开始时间
	AppType            interface{} // 应用类型：1小程序  2网站/移动应用  4生活号
	AppId              interface{} // 商家应用Id
	CreatedAt          *gtime.Time //
	UpdatedAt          *gtime.Time //
	DeletedAt          *gtime.Time //
}
