// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package share_dao

import (
    "github.com/kysion/alipay-library/alipay_model/alipay_dao/internal"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
)

type AlipayMerchantAppConfigDao = dao_interface.TIDao[internal.AlipayMerchantAppConfigColumns]

func NewAlipayMerchantAppConfig(dao ...dao_interface.IDao) AlipayMerchantAppConfigDao {
	return (AlipayMerchantAppConfigDao)(internal.NewAlipayMerchantAppConfigDao(dao...))
}

var (
	AlipayMerchantAppConfig = NewAlipayMerchantAppConfig()
)
